# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-16 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=9999)),
                ('short_hash', models.CharField(max_length=9999)),
                ('count', models.IntegerField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
