# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0002_auto_20180317_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.CharField(max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_hash',
            field=models.CharField(max_length=9999, null=True),
        ),
    ]
